### ISSUE TITLE
Couldn't find IGL-Bench on the PyPI website

### ISSUE THREAD

**Issue by yruns** [RingBDStack/IGL-Bench#1]
Great work！

However, I couldn't find IGL-Bench on the PyPI website, so I was unable to install it directly using `pip install IGL-Bench`. Additionally, I didn't find a `setup.py` or `pyproject.toml` file in the repository, so I was also unable to install it locally. Could you please check if you forgot to upload the relevant files?

**Comment by haonan-yuan** [comment]
Thanks for your kind attention to our work!

As we claimed in the README, installing this repo with `pip` is still in preparation, and we will release it very soon in October. For a quick review during this phase, you can try our `IGL-Bench` by directly cloning this repo to your local. 

Sorry for the inconvenience!
